# API密钥（根据需要添加）
# 这是一个模板文件，请在本地或Streamlit Cloud上设置您的实际API密钥

# OpenRouter API密钥
OPENROUTER_API_KEY = ""

# Serper API密钥（用于网络搜索）
SERPER_API_KEY = ""

# Smithery API密钥（用于MCP工具）
SMITHERY_API_KEY = ""

# LangChain API密钥（用于跟踪）
LANGCHAIN_API_KEY = ""

# 其他设置
[other_settings]
# 在这里添加额外的设置 